### ISSUE TITLE
WireMock 3.6.0 incompatibility

### ISSUE THREAD

**Issue by codeart1st** [wiremock/wiremock-state-extension#129]
### Proposal

https://github.com/wiremock/wiremock/releases/tag/3.6.0

Running the new 3.6.0 version of wiremock together with the wiremock-state-extension caused a problem during start. The previous version 3.5.4 looks fine. Looks like a minor API change.

```
Exception in thread "main" java.util.ServiceConfigurationError: com.github.tomakehurst.wiremock.extension.ExtensionFactory: Provider org.wiremock.extensions.state.StandaloneStateExtension could not be instantiated
2024-05-24T06:38:43.082640599Z 	at java.base/java.util.ServiceLoader.fail(Unknown Source)
2024-05-24T06:38:43.082660848Z 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(Unknown Source)
2024-05-24T06:38:43.082663856Z 	at java.base/java.util.ServiceLoader$ProviderImpl.get(Unknown Source)
2024-05-24T06:38:43.082666514Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
2024-05-24T06:38:43.082804311Z 	at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(Unknown Source)
2024-05-24T06:38:43.082809758Z 	at java.base/java.util.Spliterator.forEachRemaining(Unknown Source)
2024-05-24T06:38:43.082812155Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
2024-05-24T06:38:43.082857606Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
2024-05-24T06:38:43.082890577Z 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
2024-05-24T06:38:43.082934588Z 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
2024-05-24T06:38:43.082955746Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
2024-05-24T06:38:43.083086406Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
2024-05-24T06:38:43.083096885Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
2024-05-24T06:38:43.083101177Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
2024-05-24T06:38:43.083102659Z 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
2024-05-24T06:38:43.083160474Z 	at com.github.tomakehurst.wiremock.extension.Extensions.load(Extensions.java:106)
2024-05-24T06:38:43.083241807Z 	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:108)
2024-05-24T06:38:43.083250245Z 	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:74)
2024-05-24T06:38:43.083252411Z 	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:71)
2024-05-24T06:38:43.083319598Z 	at wiremock.Run.main(Run.java:23)
2024-05-24T06:38:43.083411203Z Caused by: java.lang.NoSuchMethodError: 'void com.github.tomakehurst.wiremock.extension.responsetemplating.TemplateEngine.<init>(java.util.Map, java.lang.Long, java.util.Set, boolean)'
2024-05-24T06:38:43.083430973Z 	at org.wiremock.extensions.state.StateExtension.<init>(StateExtension.java:64)
2024-05-24T06:38:43.083481824Z 	at org.wiremock.extensions.state.StandaloneStateExtension.<init>(StandaloneStateExtension.java:28)
2024-05-24T06:38:43.083485712Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2024-05-24T06:38:43.083507096Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2024-05-24T06:38:43.083526394Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2024-05-24T06:38:43.083545789Z 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
2024-05-24T06:38:43.083621264Z 	... 19 more
```

### Reproduction steps

```
  wiremock:
    image: wiremock/wiremock:latest-alpine
    volumes:
      - ../../common/wiremock:/home/wiremock
      - ../../common/wiremock/extensions:/var/wiremock/extensions
    ports:
      - "8888:8080"
    entrypoint: [
      "/docker-entrypoint.sh"
    ]
```

**Comment by dirkbolte** [comment]
thx for the analysis. Will have a look

**Comment by dirkbolte** [comment]
Reproduced. Unfortunately the version update introduced some build issues. Will hopefully not take too long.

**Comment by dirkbolte** [comment]
PR requires a version bump in another repo (at least I haven't found a way to achieve a build without this bump):  wiremock/gradle-wiremock-extension-plugins#17 . As soon as the other repo is merged, I will merge + release this one.

**Comment by tomakehurst** [comment]
`TemplateEngine` isn't really meant to be constructed directly.

I suggest grabbing it from `WireMockServices` in the factory method instead. This will a) ensure that any other template helpers added by the user are provided, b) protect from breaking changes to the constructor.

**Comment by dirkbolte** [comment]
@tomakehurst Thx for the pointer. Worked like a charm.

@codeart1st Issue is merged and will be released in a couple of minutes.
