### ISSUE TITLE
WireMock 3.7.0 incompatibility again

### ISSUE THREAD

**Issue by codeart1st** [wiremock/wiremock-state-extension#134]
### Proposal

https://github.com/wiremock/wiremock/releases/tag/3.7.0

Running the new 3.7.0 version of wiremock together with the wiremock-state-extension caused a problem during **usage**. The previous version 3.6.0 looks fine.

```
<html>
<body>
<!--StartFragment--><h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 java.lang.NoSuchMethodError: 'com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel.from(com.github.tomakehurst.wiremock.http.Request)'</h2>
URI: | /auth/ceres-oidcproxy-login.html
-- | --
500
java.lang.NoSuchMethodError: 'com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel.from(com.github.tomakehurst.wiremock.http.Request)'
com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-5226e402
java.lang.NoSuchMethodError: 'com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel.from(com.github.tomakehurst.wiremock.http.Request)'

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">java.lang.NoSuchMethodError: 'com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel.from(com.github.tomakehurst.wiremock.http.Request)'
	at org.wiremock.extensions.state.extensions.RecordStateEventListener.beforeResponseSent(RecordStateEventListener.java:56)
	at com.github.tomakehurst.wiremock.extension.ServeEventListener.onEvent(ServeEventListener.java:38)
	at com.github.tomakehurst.wiremock.extension.ServeEventListenerUtils.triggerListeners(ServeEventListenerUtils.java:42)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.beforeResponseSent(StubRequestHandler.java:89)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:97)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:165)
	at wiremock.jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:563)
	at wiremock.org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at wiremock.org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)</pre><!--EndFragment-->
</body>
</html>
```

### Reproduction steps

```
  wiremock:
    image: wiremock/wiremock:latest-alpine
    volumes:
      - ../../common/wiremock:/home/wiremock
      - ../../common/wiremock/extensions:/var/wiremock/extensions
    ports:
      - "8888:8080"
    entrypoint: [
      "/docker-entrypoint.sh"
    ]
```

**Comment by dirkbolte** [comment]
Reproduced.

**Comment by dirkbolte** [comment]
Release 0.8.0 should be out in a couple of minutes. Can you check whether it works for you?

**Comment by codeart1st** [comment]
Thank you very much. So fast. My use case is working again.
