### ISSUE TITLE
Fails to load extension at startup: java.lang.ClassCastException

### ISSUE THREAD

**Issue by alexandre-chopin** [wiremock/wiremock-state-extension#14]
### Proposal

When registering the extension in the Standalone context, the extension loading fails with this error:

```
Exception in thread "main" java.lang.ClassCastException: class org.wiremock.extensions.state.StandaloneStateExtension cannot be cast to class com.github.tomakehurst.wiremock.extension.Extension (org.wiremock.extensions.state.StandaloneStateExtension and com.github.tomakehurst.wiremock.extension.Extension are in unnamed module of loader 'app')
        at com.github.tomakehurst.wiremock.extension.Extensions.load(Extensions.java:182)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
        at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:378)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:374)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.github.tomakehurst.wiremock.extension.Extensions.load(Extensions.java:72)
        at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:99)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:70)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:70)
        at wiremock.Run.main(Run.java:23)
```

### Reproduction steps

Run:
```bash
java -cp wiremock-state-extension-standalone-0.0.4.jar:wiremock-standalone-3.0.0-beta-11.jar wiremock.Run --global-response-templating --extensions org.wiremock.extensions.state.StandaloneStateExtension
```

### References

Wiremock version used: https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/3.0.0-beta-11/wiremock-standalone-3.0.0-beta-11.jar

**Comment by dirkbolte** [comment]
the parameter `--extensions org.wiremock.extensions.state.StandaloneStateExtension` is not needed. The plugin should be discoverable via the `ServiceLoader` interface. For me, it starts fine with `java -cp wiremock-state-extension-standalone-0.0.4.jar:wiremock-standalone-3.0.0-beta-11.jar wiremock.Run --global-response-templating`. Can you check whether it works for you as well?

**Comment by alexandre-chopin** [comment]
When running this: `java -cp wiremock-state-extension-standalone-0.0.4.jar:wiremock-standalone-3.0.0-beta-11.jar wiremock.Run --global-response-templating`, I am getting this error:
```
Exception in thread "main" com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file /home/wiremock/./mappings/test-state.json:
Unrecognized field "withServeEventListener" (class com.github.tomakehurst.wiremock.stubbing.StubMappingCollection), not marked as ignorable
        at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:123)
        at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:250)
        at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:246)
        at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:129)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:70)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:70)
        at wiremock.Run.main(Run.java:23)
```
As for `test-state.json`, i've used the example provided in the readme.md:
```json
{
  "request": {
    "method": "POST",
    "url": "/test",
    "headers": {
      "content-type": {
        "contains": "json"
      },
      "accept": {
        "contains": "json"
      }
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "jsonBody": {
      "id": "{{randomValue length=32 type='ALPHANUMERIC' uppercase=false}}",
      "firstName": "{{jsonPath request.body '$.firstName'}}",
      "lastName": "{{jsonPath request.body '$.lastName'}}"
    }
  },
  "withServeEventListener": [
    {
      "name": "recordState",
      "parameters": {
        "context": "{{jsonPath response.body '$.id'}}",
        "state": {
          "id": "{{jsonPath response.body '$.id'}}",
          "firstName": "{{jsonPath request.body '$.firstName'}}",
          "lastName": "{{jsonPath response.body '$.lastName'}}"
        }
      }
    }
  ]
}
```

**Comment by dirkbolte** [comment]
There was a bug in the documentation: `withServeEventListener` -> `serveEventListeners` . Your example should therefore be:

```json
{
  "request": {
    "method": "POST",
    "url": "/test",
    "headers": {
      "content-type": {
        "contains": "json"
      },
      "accept": {
        "contains": "json"
      }
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "jsonBody": {
      "id": "{{randomValue length=32 type='ALPHANUMERIC' uppercase=false}}",
      "firstName": "{{jsonPath request.body '$.firstName'}}",
      "lastName": "{{jsonPath request.body '$.lastName'}}"
    }
  },
  "serveEventListeners": [
    {
      "name": "recordState",
      "parameters": {
        "context": "{{jsonPath response.body '$.id'}}",
        "state": {
          "id": "{{jsonPath response.body '$.id'}}",
          "firstName": "{{jsonPath request.body '$.firstName'}}",
          "lastName": "{{jsonPath response.body '$.lastName'}}"
        }
      }
    }
  ]
}

```

**Comment by alexandre-chopin** [comment]
That was it, the extension loads properly now 👍

**Comment by dirkbolte** [comment]
merged.
